//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ZigBeeCoordinator.Lib.Models.Db
{
    public partial class ZigBeeDeviceLog
    {
    	private readonly static ZigBeeDeviceLogFinder _finder = new ZigBeeDeviceLogFinder();
    	public static ZigBeeDeviceLogFinder Finder { get { return _finder; } }
    
    	static ZigBeeDeviceLog() {
    		ZigBeeCoordinator.Lib.Infrastructure.IocContainer.Instance.Compose(_finder);
    	}
    
        #region Primitive Properties
    
        public virtual int ZigBeeDeviceLogId
        {
            get;
            set;
        }
    
        public virtual int ZigBeeDeviceId
        {
            get { return _zigBeeDeviceId; }
            set
            {
                if (_zigBeeDeviceId != value)
                {
                    if (ZigBeeDevice != null && ZigBeeDevice.ZigBeeDeviceId != value)
                    {
                        ZigBeeDevice = null;
                    }
                    _zigBeeDeviceId = value;
                }
            }
        }
        private int _zigBeeDeviceId;
    
        public virtual byte[] PacketData
        {
            get;
            set;
        }
    
        public virtual System.DateTime DateTime
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ZigBeeDevice ZigBeeDevice
        {
            get { return _zigBeeDevice; }
            set
            {
                if (!ReferenceEquals(_zigBeeDevice, value))
                {
                    var previousValue = _zigBeeDevice;
                    _zigBeeDevice = value;
                    FixupZigBeeDevice(previousValue);
                }
            }
        }
        private ZigBeeDevice _zigBeeDevice;

        #endregion
        #region Association Fixup
    
        private void FixupZigBeeDevice(ZigBeeDevice previousValue)
        {
            if (previousValue != null && previousValue.ZigBeeDeviceLogs.Contains(this))
            {
                previousValue.ZigBeeDeviceLogs.Remove(this);
            }
    
            if (ZigBeeDevice != null)
            {
                if (!ZigBeeDevice.ZigBeeDeviceLogs.Contains(this))
                {
                    ZigBeeDevice.ZigBeeDeviceLogs.Add(this);
                }
                if (ZigBeeDeviceId != ZigBeeDevice.ZigBeeDeviceId)
                {
                    ZigBeeDeviceId = ZigBeeDevice.ZigBeeDeviceId;
                }
            }
        }

        #endregion
    }
    
    public partial class ZigBeeDeviceLogFinder {
    }
    
}
