//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace ZigBeeCoordinator.Lib.Models.Db
{
    public partial class ZigBeeCoordinatorEntities : ObjectContext
    {
        public const string ConnectionString = "name=ZigBeeCoordinatorEntities";
        public const string ContainerName = "ZigBeeCoordinatorEntities";
    
        #region Constructors
    
        public ZigBeeCoordinatorEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public ZigBeeCoordinatorEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        public ZigBeeCoordinatorEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Capability> Capabilities
        {
            get { return _capabilities  ?? (_capabilities = CreateObjectSet<Capability>("Capabilities")); }
        }
        private ObjectSet<Capability> _capabilities;
    
        public ObjectSet<ZigBeeDevice> ZigBeeDevices
        {
            get { return _zigBeeDevices  ?? (_zigBeeDevices = CreateObjectSet<ZigBeeDevice>("ZigBeeDevices")); }
        }
        private ObjectSet<ZigBeeDevice> _zigBeeDevices;
    
        public ObjectSet<ZigBeeDeviceLog> ZigBeeDeviceLogs
        {
            get { return _zigBeeDeviceLogs  ?? (_zigBeeDeviceLogs = CreateObjectSet<ZigBeeDeviceLog>("ZigBeeDeviceLogs")); }
        }
        private ObjectSet<ZigBeeDeviceLog> _zigBeeDeviceLogs;
    
        public ObjectSet<ZigBeeDeviceType> ZigBeeDeviceTypes
        {
            get { return _zigBeeDeviceTypes  ?? (_zigBeeDeviceTypes = CreateObjectSet<ZigBeeDeviceType>("ZigBeeDeviceTypes")); }
        }
        private ObjectSet<ZigBeeDeviceType> _zigBeeDeviceTypes;
    
        public ObjectSet<CoordinatorUser> CoordinatorUsers
        {
            get { return _coordinatorUsers  ?? (_coordinatorUsers = CreateObjectSet<CoordinatorUser>("CoordinatorUsers")); }
        }
        private ObjectSet<CoordinatorUser> _coordinatorUsers;
    
        public ObjectSet<WirelessScaleData> WirelessScaleDatas
        {
            get { return _wirelessScaleDatas  ?? (_wirelessScaleDatas = CreateObjectSet<WirelessScaleData>("WirelessScaleDatas")); }
        }
        private ObjectSet<WirelessScaleData> _wirelessScaleDatas;
    
        public ObjectSet<UserSetting> UserSettings
        {
            get { return _userSettings  ?? (_userSettings = CreateObjectSet<UserSetting>("UserSettings")); }
        }
        private ObjectSet<UserSetting> _userSettings;

        #endregion
    }
}
