//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace ZigBeeCoordinator.Lib.Models.Db
{
    public partial class ZigBeeDeviceType
    {
    	private readonly static ZigBeeDeviceTypeFinder _finder = new ZigBeeDeviceTypeFinder();
    	public static ZigBeeDeviceTypeFinder Finder { get { return _finder; } }
    
    	static ZigBeeDeviceType() {
    		ZigBeeCoordinator.Lib.Infrastructure.IocContainer.Instance.Compose(_finder);
    	}
    
        #region Primitive Properties
    
        public virtual int ZigBeeDeviceTypeId
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<ZigBeeDevice> ZigBeeDevices
        {
            get
            {
                if (_zigBeeDevices == null)
                {
                    var newCollection = new FixupCollection<ZigBeeDevice>();
                    newCollection.CollectionChanged += FixupZigBeeDevices;
                    _zigBeeDevices = newCollection;
                }
                return _zigBeeDevices;
            }
            set
            {
                if (!ReferenceEquals(_zigBeeDevices, value))
                {
                    var previousValue = _zigBeeDevices as FixupCollection<ZigBeeDevice>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupZigBeeDevices;
                    }
                    _zigBeeDevices = value;
                    var newValue = value as FixupCollection<ZigBeeDevice>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupZigBeeDevices;
                    }
                }
            }
        }
        private ICollection<ZigBeeDevice> _zigBeeDevices;

        #endregion
        #region Association Fixup
    
        private void FixupZigBeeDevices(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ZigBeeDevice item in e.NewItems)
                {
                    item.ZigBeeDeviceType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ZigBeeDevice item in e.OldItems)
                {
                    if (ReferenceEquals(item.ZigBeeDeviceType, this))
                    {
                        item.ZigBeeDeviceType = null;
                    }
                }
            }
        }

        #endregion
    }
    
    public partial class ZigBeeDeviceTypeFinder {
    }
    
}
